// Build hook: רץ אוטומטית על כל `flutter build` / `flutter run` /
// `flutter pub get` ומחולל את `lib/settings/search/settings_search_index.g.dart`
// המאחד את כל הצהרות `static const List<SettingsSearchEntry> searchEntries`
// בקבצים תחת `lib/settings/`.

// `package:hooks` מוגדרת כ-dev_dependency כי היא נחוצה רק לסקריפט הזה
// בזמן build ולא ל-runtime של האפליקציה.
// ignore: depend_on_referenced_packages
import 'dart:io';

// ignore: depend_on_referenced_packages
import 'package:hooks/hooks.dart';

const _outputAsset = 'lib/settings/search/settings_search_index.g.dart';

void main(List<String> args) async {
  await build(args, (input, output) async {
    final packageRoot = Directory.fromUri(input.packageRoot);
    await _generateSearchIndex(packageRoot);
  });
}

Future<void> _generateSearchIndex(Directory packageRoot) async {
  final settingsRoot = Directory.fromUri(
    packageRoot.uri.resolve('lib/settings/'),
  );
  if (!settingsRoot.existsSync()) {
    return;
  }

  final packageName = _readPackageName(packageRoot);

  final declarations = <_FoundDecl>[];
  for (final entity
      in settingsRoot.listSync(recursive: true, followLinks: false)) {
    if (entity is! File) continue;
    if (!entity.path.endsWith('.dart')) continue;
    if (entity.path.endsWith('.g.dart')) continue;

    final content = entity.readAsStringSync();
    final relPath = _relativeToPackage(entity, packageRoot);
    declarations.addAll(_findDeclarations(content, relPath, packageName));
  }

  // גם כשהרשימה ריקה — נכתוב אינדקס ריק (במקום לוותר). אחרת ה-.g.dart
  // הישן יישאר עם imports/entries שלא קיימים יותר ויגרום לשגיאות
  // קומפילציה או לתוצאות חיפוש פנטומיות.

  declarations.sort((a, b) {
    final tabCmp = a.tabValue.compareTo(b.tabValue);
    if (tabCmp != 0) return tabCmp;
    return a.className.compareTo(b.className);
  });

  final imports = <String>{};
  final spreads = <String>[];
  for (final decl in declarations) {
    imports.add(decl.importPath);
    spreads.add('  ...${decl.className}.searchEntries,');
  }
  final sortedImports = imports.toList()..sort();

  final buffer = StringBuffer()
    ..writeln('// GENERATED CODE — DO NOT MODIFY BY HAND.')
    ..writeln('// Generated by hook/build.dart on every Flutter build.')
    ..writeln('//')
    ..writeln('// אינדקס חיפוש מאוחד של ההגדרות. נוצר אוטומטית מתוך')
    ..writeln('// הצהרות `static const searchEntries` בקבצים תחת lib/settings/.')
    ..writeln('')
    ..writeln(
        "import 'package:$packageName/settings/search/settings_search_models.dart';");
  for (final imp in sortedImports) {
    buffer.writeln("import '$imp';");
  }
  buffer
    ..writeln('')
    ..writeln('/// כל פריטי החיפוש שנאספו מהטאבים והפנלים.')
    ..writeln(
        'const List<SettingsSearchEntry> kGeneratedSettingsSearchEntries = [');
  for (final line in spreads) {
    buffer.writeln(line);
  }
  buffer.writeln('];');

  final outputFile = File.fromUri(packageRoot.uri.resolve(_outputAsset));
  final newContent = buffer.toString();

  // כתוב רק אם הייתה שינוי, כדי לא לטריגר rebuild מיותר.
  if (outputFile.existsSync()) {
    final existing = outputFile.readAsStringSync();
    if (existing == newContent) return;
  }
  outputFile.parent.createSync(recursive: true);
  outputFile.writeAsStringSync(newContent);
}

String _relativeToPackage(File file, Directory packageRoot) {
  final rootPath = packageRoot.path.replaceAll('\\', '/');
  final filePath = file.path.replaceAll('\\', '/');
  if (filePath.startsWith(rootPath)) {
    var rel = filePath.substring(rootPath.length);
    if (rel.startsWith('/')) rel = rel.substring(1);
    return rel;
  }
  return filePath;
}

List<_FoundDecl> _findDeclarations(
    String content, String relPath, String packageName) {
  // הסר מחרוזות והערות לפני סריקה, כדי שאיזון הסוגריים יהיה מהימן
  // ולא יוטעה על-ידי `}` או `{` בתוך מחרוזת/הערה.
  final cleaned = _stripStringsAndComments(content);

  final results = <_FoundDecl>[];
  // מזהה כל הצהרת מחלקה (לרבות final/base/sealed/abstract/interface/mixin
  // ו-generics, גם בלי extends).
  final classMatches = RegExp(
    r'(?:abstract\s+|base\s+|final\s+|sealed\s+|interface\s+|mixin\s+)?'
    r'class\s+(\w+)\s*(?:<[^{>]+>)?\s*'
    r'(?:extends\s+[^{]+|with\s+[^{]+|implements\s+[^{]+)*\s*\{',
  ).allMatches(cleaned);

  for (final classMatch in classMatches) {
    final className = classMatch.group(1)!;
    final classBody = _extractBalanced(cleaned, classMatch.end - 1, '{', '}');
    if (classBody == null) continue;
    if (!classBody.contains('searchEntries')) continue;

    final entriesDecl = RegExp(
      r'static\s+const\s+List<SettingsSearchEntry>\s+searchEntries\s*=\s*\[',
    ).firstMatch(classBody);
    if (entriesDecl == null) continue;

    final tabMatch =
        RegExp(r'tab:\s*SettingsTab\.(\w+)').firstMatch(classBody);
    final tabValue = tabMatch?.group(1) ?? 'zzz';

    final libIndex = relPath.indexOf('lib/');
    final libRelPath = libIndex >= 0
        ? relPath.substring(libIndex + 'lib/'.length)
        : relPath;

    results.add(_FoundDecl(
      className: className,
      importPath: 'package:$packageName/$libRelPath',
      tabValue: tabValue,
    ));
  }

  return results;
}

/// מחליף מחרוזות והערות ברווחים שווי-אורך, כך שאינדקסי תווים נשארים
/// תקפים אבל אין סיכוי שתוכן בתוך string/comment יזהם את הסריקה.
String _stripStringsAndComments(String src) {
  final out = StringBuffer();
  var i = 0;
  while (i < src.length) {
    final c = src[i];
    final c2 = (i + 1 < src.length) ? src[i + 1] : '';

    // הערה חד-שורתית //
    if (c == '/' && c2 == '/') {
      while (i < src.length && src[i] != '\n') {
        out.write(src[i] == '\n' ? '\n' : ' ');
        i++;
      }
      continue;
    }
    // הערה רב-שורתית /* ... */
    if (c == '/' && c2 == '*') {
      while (i < src.length) {
        if (i + 1 < src.length && src[i] == '*' && src[i + 1] == '/') {
          out.write('  ');
          i += 2;
          break;
        }
        out.write(src[i] == '\n' ? '\n' : ' ');
        i++;
      }
      continue;
    }
    // מחרוזת raw או רגילה, single/double, single/triple quoted
    if (c == "'" || c == '"' || (c == 'r' && (c2 == '"' || c2 == "'"))) {
      var idx = (c == 'r') ? i + 1 : i;
      final quote = src[idx];
      // triple-quote?
      final isTriple = idx + 2 < src.length &&
          src[idx + 1] == quote &&
          src[idx + 2] == quote;
      // העתק את התווים שלפני המרכאות (במקרה raw — 'r')
      while (i <= idx) {
        out.write(src[i] == '\n' ? '\n' : ' ');
        i++;
      }
      if (isTriple) {
        // דלג על שני התווים הנוספים של triple-quote
        out.write('  ');
        i += 2;
        while (i + 2 < src.length) {
          if (src[i] == quote && src[i + 1] == quote && src[i + 2] == quote) {
            out.write('   ');
            i += 3;
            break;
          }
          out.write(src[i] == '\n' ? '\n' : ' ');
          i++;
        }
      } else {
        // raw strings (`r'...'`) לא מבצעים escape — אז דלג רק במחרוזות רגילות
        final isRaw = (c == 'r');
        while (i < src.length) {
          if (!isRaw && src[i] == '\\' && i + 1 < src.length) {
            // דלג על escape sequence (כגון \" \' \\ \n) — שני תווים
            out.write(src[i + 1] == '\n' ? ' \n' : '  ');
            i += 2;
            continue;
          }
          if (src[i] == quote) {
            out.write(' ');
            i++;
            break;
          }
          out.write(src[i] == '\n' ? '\n' : ' ');
          i++;
        }
      }
      continue;
    }
    out.write(c);
    i++;
  }
  return out.toString();
}

/// קורא את שם החבילה מתוך `pubspec.yaml` של ה-packageRoot כדי לבנות נתיבי
/// `package:` נכונים במקום לקודד שם קשיח. נכשל בקול אם השדה לא נמצא —
/// עדיף שגיאה ברורה מאשר אינדקס שגוי בשקט.
String _readPackageName(Directory packageRoot) {
  final pubspec = File.fromUri(packageRoot.uri.resolve('pubspec.yaml'));
  if (!pubspec.existsSync()) {
    throw StateError('pubspec.yaml not found at: ${pubspec.path}');
  }
  final match = RegExp(r'^name:\s*([A-Za-z_][A-Za-z0-9_]*)', multiLine: true)
      .firstMatch(pubspec.readAsStringSync());
  if (match == null) {
    throw StateError('Could not parse package name from ${pubspec.path}');
  }
  return match.group(1)!;
}

String? _extractBalanced(String src, int openIdx, String open, String close) {
  if (openIdx < 0 || openIdx >= src.length || src[openIdx] != open) return null;
  var depth = 0;
  for (var i = openIdx; i < src.length; i++) {
    final c = src[i];
    if (c == open) depth++;
    if (c == close) {
      depth--;
      if (depth == 0) return src.substring(openIdx + 1, i);
    }
  }
  return null;
}

class _FoundDecl {
  final String className;
  final String importPath;
  final String tabValue;
  _FoundDecl({
    required this.className,
    required this.importPath,
    required this.tabValue,
  });
}
