// ignore_for_file: avoid_print
//
// סקריפט בנייה: סורק את כל קבצי ה-Dart תחת lib/settings/ ואוסף את כל
// הצהרות `static const List<SettingsSearchEntry> searchEntries`,
// ומחולל את lib/settings/search/settings_search_index.g.dart המכיל
// אינדקס מאוחד של כל הפריטים.
//
// הפעלה ידנית:  `dart run tool/generate_search_index.dart`
// ב-CI:         הוסף לפני `flutter analyze`/`flutter build` כצעד עצמאי.
//
// סקריפט עצמאי (לא מסתמך על package:hooks/build_runner) — מתאים
// לכל סביבה שמריצה flutter ללא תלות בלוקאלי שלך.

import 'dart:io';

const _settingsRoot = 'lib/settings';
const _outputPath = 'lib/settings/search/settings_search_index.g.dart';

void main(List<String> args) {
  final root = Directory(_settingsRoot);
  if (!root.existsSync()) {
    stderr.writeln('Settings directory not found: $_settingsRoot');
    exit(1);
  }

  final declarations = <_FoundDecl>[];
  for (final entity in root.listSync(recursive: true, followLinks: false)) {
    if (entity is! File) continue;
    if (!entity.path.endsWith('.dart')) continue;
    if (entity.path.endsWith('.g.dart')) continue;

    final content = entity.readAsStringSync();
    declarations.addAll(_findDeclarations(content, _normalizePath(entity.path)));
  }

  declarations.sort((a, b) {
    final tabCmp = a.tabValue.compareTo(b.tabValue);
    if (tabCmp != 0) return tabCmp;
    return a.className.compareTo(b.className);
  });

  // גם כשהרשימה ריקה — נכתוב אינדקס ריק (במקום לוותר). אחרת ה-.g.dart
  // הישן יישאר עם imports/entries שלא קיימים יותר ויגרום לשגיאות
  // קומפילציה או לתוצאות חיפוש פנטומיות.

  final imports = <String>{};
  final spreads = <String>[];
  for (final decl in declarations) {
    imports.add(decl.importPath);
    spreads.add('  ...${decl.className}.searchEntries,');
  }
  final sortedImports = imports.toList()..sort();

  final buffer = StringBuffer()
    ..writeln('// GENERATED CODE — DO NOT MODIFY BY HAND.')
    ..writeln('// Generated by tool/generate_search_index.dart')
    ..writeln('//')
    ..writeln('// אינדקס חיפוש מאוחד של ההגדרות. נוצר אוטומטית מתוך')
    ..writeln('// הצהרות `static const searchEntries` בקבצים תחת lib/settings/.')
    ..writeln('')
    ..writeln(
        "import 'package:otzaria/settings/search/settings_search_models.dart';");
  for (final imp in sortedImports) {
    buffer.writeln("import '$imp';");
  }
  buffer
    ..writeln('')
    ..writeln('/// כל פריטי החיפוש שנאספו מהטאבים והפנלים.')
    ..writeln(
        'const List<SettingsSearchEntry> kGeneratedSettingsSearchEntries = [');
  for (final line in spreads) {
    buffer.writeln(line);
  }
  buffer.writeln('];');

  final outputFile = File(_outputPath);
  final newContent = buffer.toString();

  // כתוב רק אם השתנה — מונע מודיפיקציות מיותרות שיגרמו ל-rebuild.
  if (outputFile.existsSync()) {
    final existing = outputFile.readAsStringSync();
    if (existing == newContent) {
      stdout.writeln(
          'Index up-to-date: $_outputPath (${declarations.length} declarations).');
      return;
    }
  }
  outputFile.parent.createSync(recursive: true);
  outputFile.writeAsStringSync(newContent);
  stdout.writeln(
      'Generated $_outputPath with ${declarations.length} declaration(s).');
}

List<_FoundDecl> _findDeclarations(String content, String relPath) {
  // הסר מחרוזות והערות לפני סריקה, כדי שאיזון הסוגריים יהיה מהימן
  // ולא יוטעה על-ידי `}` או `{` בתוך מחרוזת/הערה.
  final cleaned = _stripStringsAndComments(content);

  final results = <_FoundDecl>[];
  final classMatches = RegExp(
    r'(?:abstract\s+|base\s+|final\s+|sealed\s+|interface\s+|mixin\s+)?'
    r'class\s+(\w+)\s*(?:<[^{>]+>)?\s*'
    r'(?:extends\s+[^{]+|with\s+[^{]+|implements\s+[^{]+)*\s*\{',
  ).allMatches(cleaned);

  for (final classMatch in classMatches) {
    final className = classMatch.group(1)!;
    final classBody = _extractBalanced(cleaned, classMatch.end - 1, '{', '}');
    if (classBody == null) continue;
    if (!classBody.contains('searchEntries')) continue;

    final entriesDecl = RegExp(
      r'static\s+const\s+List<SettingsSearchEntry>\s+searchEntries\s*=\s*\[',
    ).firstMatch(classBody);
    if (entriesDecl == null) continue;

    final tabMatch =
        RegExp(r'tab:\s*SettingsTab\.(\w+)').firstMatch(classBody);
    final tabValue = tabMatch?.group(1) ?? 'zzz';

    final libIndex = relPath.indexOf('lib/');
    final libRelPath = libIndex >= 0
        ? relPath.substring(libIndex + 'lib/'.length)
        : relPath;

    results.add(_FoundDecl(
      className: className,
      importPath: 'package:otzaria/$libRelPath',
      tabValue: tabValue,
    ));
  }

  return results;
}

/// מחליף מחרוזות והערות ברווחים שווי-אורך, כך שאינדקסי תווים נשארים
/// תקפים אבל אין סיכוי שתוכן בתוך string/comment יזהם את הסריקה.
String _stripStringsAndComments(String src) {
  final out = StringBuffer();
  var i = 0;
  while (i < src.length) {
    final c = src[i];
    final c2 = (i + 1 < src.length) ? src[i + 1] : '';

    // הערה חד-שורתית //
    if (c == '/' && c2 == '/') {
      while (i < src.length && src[i] != '\n') {
        out.write(src[i] == '\n' ? '\n' : ' ');
        i++;
      }
      continue;
    }
    // הערה רב-שורתית /* ... */
    if (c == '/' && c2 == '*') {
      while (i < src.length) {
        if (i + 1 < src.length && src[i] == '*' && src[i + 1] == '/') {
          out.write('  ');
          i += 2;
          break;
        }
        out.write(src[i] == '\n' ? '\n' : ' ');
        i++;
      }
      continue;
    }
    // מחרוזת raw או רגילה, single/double, single/triple quoted
    if (c == "'" || c == '"' || (c == 'r' && (c2 == '"' || c2 == "'"))) {
      var idx = (c == 'r') ? i + 1 : i;
      final quote = src[idx];
      final isTriple = idx + 2 < src.length &&
          src[idx + 1] == quote &&
          src[idx + 2] == quote;
      // העתק את התווים שלפני המרכאות (במקרה raw — 'r')
      while (i <= idx) {
        out.write(src[i] == '\n' ? '\n' : ' ');
        i++;
      }
      if (isTriple) {
        out.write('  ');
        i += 2;
        while (i + 2 < src.length) {
          if (src[i] == quote && src[i + 1] == quote && src[i + 2] == quote) {
            out.write('   ');
            i += 3;
            break;
          }
          out.write(src[i] == '\n' ? '\n' : ' ');
          i++;
        }
      } else {
        final isRaw = (c == 'r');
        while (i < src.length) {
          if (!isRaw && src[i] == '\\' && i + 1 < src.length) {
            out.write(src[i + 1] == '\n' ? ' \n' : '  ');
            i += 2;
            continue;
          }
          if (src[i] == quote) {
            out.write(' ');
            i++;
            break;
          }
          out.write(src[i] == '\n' ? '\n' : ' ');
          i++;
        }
      }
      continue;
    }
    out.write(c);
    i++;
  }
  return out.toString();
}

String? _extractBalanced(String src, int openIdx, String open, String close) {
  if (openIdx < 0 || openIdx >= src.length || src[openIdx] != open) return null;
  var depth = 0;
  for (var i = openIdx; i < src.length; i++) {
    final c = src[i];
    if (c == open) depth++;
    if (c == close) {
      depth--;
      if (depth == 0) return src.substring(openIdx + 1, i);
    }
  }
  return null;
}

String _normalizePath(String path) => path.replaceAll('\\', '/');

class _FoundDecl {
  final String className;
  final String importPath;
  final String tabValue;
  _FoundDecl({
    required this.className,
    required this.importPath,
    required this.tabValue,
  });
}
