; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "אוצריא"
#define MyAppVersion "0.9.95"
#define MyAppPublisher "sivan22"
#define MyAppURL "https://github.com/otzaria/otzaria"
#define MyAppExeName "otzaria.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{EEC4F712-CD05-4D15-A753-509E840A51A5}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
PrivilegesRequiredOverridesAllowed=dialog
DefaultDirName={code:GetDefaultInstallDir}
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
OutputDir=.
OutputBaseFilename=otzaria-{#MyAppVersion}-windows-full
SetupIconFile=white_sketch128x128.ico
; תמונת האשף בעמודי "ברוכים הבאים" ו"סיום" (אנכית, 164x314 + רזולוציות @2x/@3x ל-HiDPI)
WizardImageFile=wizard_large.bmp,wizard_large@2x.bmp,wizard_large@3x.bmp
; תמונה קטנה בפינת כל עמוד אחר (55x58 + רזולוציות גבוהות)
WizardSmallImageFile=wizard_small.bmp,wizard_small@2x.bmp,wizard_small@3x.bmp
Compression=lzma
SolidCompression=yes
; Disable compression for DLL files to prevent corruption
CompressionThreads=1
WizardStyle=modern
DisableDirPage=no
; ChangesEnvironment=yes נדרש כדי שעדכון ל-PATH (במשימת addtopath) ייכנס
; לתוקף מיד עבור תהליכים חדשים ללא צורך ב-logoff.
ChangesEnvironment=yes

[InstallDelete]
; מחיקת ספריית נתונים ישנה לפני פריסת מסד הנתונים החדש
Type: filesandordirs; Name: "{code:GetSelectedBooksPath}"

[Dirs]
Name: "{code:GetDataDir}"; Permissions: users-modify
Name: "{code:GetDataDir}\books"; Permissions: users-modify
Name: "{code:GetDataDir}\index"; Permissions: users-modify

[Registry]
Root: HKA; Subkey: "Software\Classes\otzaria"; ValueType: string; ValueName: ""; ValueData: "URL:Otzaria Protocol"; Flags: uninsdeletekeyifempty
Root: HKA; Subkey: "Software\Classes\otzaria"; ValueType: string; ValueName: "URL Protocol"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\otzaria\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName}"; Flags: uninsdeletekeyifempty
Root: HKA; Subkey: "Software\Classes\otzaria\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""; Flags: uninsdeletekeyifempty
; הוספת {app} ל-PATH של המשתמש כדי שניתן יהיה להריץ ‎`otzaria pack-plugin`‎
; ישירות מהטרמינל. ה-Check מונע כפילויות; ההסרה ב-CurUninstallStepChanged.
Root: HKCU; Subkey: "Environment"; ValueType: expandsz; ValueName: "Path"; ValueData: "{olddata};{app}"; Flags: preservestringtype; Check: NeedsAddPath(ExpandConstant('{app}')); Tasks: addtopath

[Languages]
Name: "hebrew"; MessagesFile: "compiler:Languages\Hebrew.isl"

[Code]

const
  // קבועי פריסה לדף "תכונות עיקריות" - Inno Setup לא תומך ב-const מקומי בתוך פרוצדורה.
  FEATURES_GAP_X = 14;
  FEATURES_GAP_Y = 8;
  FEATURES_LABEL_H = 18;

var
  CompPage: TWizardPage;
  WV2Check: TCheckBox;
  WV2Label: TLabel;
  InstallWV2: Boolean;

  BooksPage: TWizardPage;
  BooksPathEdit: TEdit;
  BooksPathBrowseBtn: TButton;
  BooksWarnLabel: TLabel;
  SelectedBooksPath: String;

  FeaturesPage: TWizardPage;
  SlideshowImage: TBitmapImage;
  SlideshowTimerId: LongWord;
  SlideshowTimerCallback: LongWord;
  SlideshowIndex: Integer;

  // אם המשתמש בחר במהלך ההסרה למחוק גם את כל הנתונים והספרים, לא רק את
  // קבצי האפליקציה. ברירת המחדל False — נשמר כדי לא לאבד נתונים בעדכון
  // שקט (Inno Setup מריץ את ה-uninstaller הישן עם /SILENT).
  DeleteUserDataOnUninstall: Boolean;

// TTimer לא זמין ב-Pascal Script של Inno Setup; נשתמש ב-Windows API.
function SetTimer(hWnd, nIDEvent, uElapse, lpTimerFunc: LongWord): LongWord;
  external 'SetTimer@user32.dll stdcall';
function KillTimer(hWnd, nIDEvent: LongWord): LongWord;
  external 'KillTimer@user32.dll stdcall';

function TryGetInstallDirFromRegistry(RootKey: Integer; const SubKey: String; var InstallDir: String): Boolean;
begin
  Result := RegQueryStringValue(RootKey, SubKey, 'Inno Setup: App Path', InstallDir);
  if (not Result) or (InstallDir = '') then
    Result := RegQueryStringValue(RootKey, SubKey, 'InstallLocation', InstallDir);

  if Result and DirExists(InstallDir) then
    exit;

  InstallDir := '';
  Result := False;
end;

function FindPreviousInstallDir(): String;
var
  InstallDir: String;
  LegacyDir: String;
  UninstallKey: String;
begin
  UninstallKey := 'Software\Microsoft\Windows\CurrentVersion\Uninstall\{EEC4F712-CD05-4D15-A753-509E840A51A5}_is1';

  if TryGetInstallDirFromRegistry(HKLM64, UninstallKey, InstallDir) or
     TryGetInstallDirFromRegistry(HKCU, UninstallKey, InstallDir) then
  begin
    Result := InstallDir;
    exit;
  end;

  LegacyDir := 'C:\אוצריא';
  if DirExists(LegacyDir) then
  begin
    Result := LegacyDir;
    exit;
  end;

  LegacyDir := ExpandConstant('{autopf}\אוצריא');
  if DirExists(LegacyDir) then
  begin
    Result := LegacyDir;
    exit;
  end;

  LegacyDir := ExpandConstant('{autopf}\Otzaria');
  if DirExists(LegacyDir) then
  begin
    Result := LegacyDir;
    exit;
  end;

  Result := '';
end;

function GetDefaultInstallDir(Param: String): String;
begin
  Result := FindPreviousInstallDir();
  if Result = '' then
    Result := ExpandConstant('{autopf}\Otzaria');
end;

function GetDataDir(Param: String): String;
begin
  if IsAdminInstallMode then
    Result := ExpandConstant('{commonappdata}\otzaria')
  else
    Result := ExpandConstant('{userappdata}\otzaria');
end;

function GetSelectedBooksPath(Param: String): String;
begin
  if SelectedBooksPath <> '' then
    Result := SelectedBooksPath
  else
    Result := GetDataDir('') + '\books';
end;

// משמר את backups באיפוס הגדרות — כדי שקובצי גיבוי ישרדו ויאפשרו שחזור
// הערות/סימניות/נתוני תוספים דרך "שחזור מגיבוי". books נמחק כי מותקן מחדש.
procedure DelTreeExceptBackups(Path: String);
var
  FindRec: TFindRec;
  ChildPath: String;
begin
  if not DirExists(Path) then
    exit;

  if FindFirst(Path + '\*', FindRec) then
  begin
    try
      repeat
        if (FindRec.Name <> '.') and (FindRec.Name <> '..') then
        begin
          ChildPath := Path + '\' + FindRec.Name;

          if (FindRec.Attributes and FILE_ATTRIBUTE_DIRECTORY) <> 0 then
          begin
            if Lowercase(FindRec.Name) <> 'backups' then
            begin
              DelTreeExceptBackups(ChildPath);
              RemoveDir(ChildPath);
            end;
          end
          else
            DeleteFile(ChildPath);
        end;
      until not FindNext(FindRec);
    finally
      FindClose(FindRec);
    end;
  end;

  RemoveDir(Path);
end;

// ─── בדיקות רכיבי מערכת ───────────────────────────────────────────────────

function GetWebView2Version: String;
var
  Version: String;
begin
  if RegQueryStringValue(HKLM64,
      'SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}',
      'pv', Version) then
  begin
    Result := Version;
    exit;
  end;
  if RegQueryStringValue(HKCU,
      'SOFTWARE\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}',
      'pv', Version) then
    Result := Version
  else
    Result := '';
end;

function WebView2NeedsInstall: Boolean;
begin
  Result := GetWebView2Version = '';
end;

function InitializeSetup(): Boolean;
var
  DataPath, OldPath: String;
begin
  Result := True;
  DataPath := GetDataDir('');
  OldPath := 'C:\אוצריא';

  // בדיקה אם יש התקנה ישנה בנתיב העברי
  if DirExists(OldPath) then
  begin
    if MsgBox('נמצאה התקנה ישנה ב-' + OldPath + #13#10 +
              'ספריית הספרים עוברת לנתיב חדש: ' + DataPath + #13#10#13#10 +
              'האם להעביר את הנתונים למיקום החדש?',
              mbConfirmation, MB_YESNO) = IDYES then
    begin
      // המשתמש יצטרך להעביר ידנית או שנוסיף קוד העברה
      MsgBox('לאחר ההתקנה, תוכל להעביר את הנתונים מ-' + OldPath + ' ל-' + DataPath, mbInformation, MB_OK);
    end;
  end;

  // האזהרה על מחיקת ספרים קיימים מוצגת בדף בחירת תיקיית הספרים

  // אתחול ברירות מחדל — גם להתקנה שקטה (/SILENT, /VERYSILENT)
  InstallWV2 := WebView2NeedsInstall;
  SelectedBooksPath := GetDataDir('') + '\books';
end;

// ─── בניית עמוד בחירת רכיבים ───────────────────────────────────────────────

procedure CreateComponentsPage;
var
  WV2Version: String;
  WV2Status: String;
  WV2Color: TColor;
  TopY: Integer;
  HeaderLabel: TLabel;
begin
  CompPage := CreateCustomPage(wpSelectDir,
    'בחירת רכיבי מערכת להתקנה',
    'בדיקת הרכיבים הנדרשים לאפליקציה');

  WV2Version := GetWebView2Version;

  // כותרת הסבר
  HeaderLabel := TLabel.Create(CompPage);
  HeaderLabel.Parent := CompPage.Surface;
  HeaderLabel.Left   := 0;
  HeaderLabel.Top    := 0;
  HeaderLabel.Width  := CompPage.SurfaceWidth;
  HeaderLabel.AutoSize := False;
  HeaderLabel.WordWrap := True;
  HeaderLabel.Caption :=
    'בדיקת רכיבי Microsoft הנדרשים לאוצריא.' + #13#10 +
    'בכתום: חסר — מומלץ להתקין.' + #13#10 +
    'בירוק: קיים — אין צורך בפעולה.';
  HeaderLabel.Height := ScaleY(60);  // 3 שורות קצרות, בלי עודף ריפוד

  TopY := HeaderLabel.Height + ScaleY(6);

  // ─── WebView2 Runtime ─────────────────────────────────────────────────────
  // הערה: Visual C++ Runtime כבר לא מותקן ע"י המתקין — ה-DLLs נארזים
  // app-local ליד otzaria.exe (ראה .github/workflows/build-and-announce.yml
  // והשלב "Bundle latest VC++ Redistributable runtime DLLs"), כך שאין
  // צורך לבדוק / להתקין אותו בזמן ההתקנה. המתקין FULL מציג עכשיו רק
  // את ה-WebView2 בדף בחירת רכיבי המערכת.
  WV2Check := TCheckBox.Create(CompPage);
  WV2Check.Parent  := CompPage.Surface;
  WV2Check.Left    := 0;
  WV2Check.Top     := TopY;
  WV2Check.Width   := CompPage.SurfaceWidth;
  WV2Check.Height  := ScaleY(20);
  WV2Check.Caption := 'Microsoft WebView2 Runtime';

  // WebView2 אינו חובה — משמש רק למערכת הפלאגינים (לא לקריאה/חיפוש/סימניות)
  if WV2Version = '' then
  begin
    WV2Status := '⚠ חסר — מומלץ להתקין. ללא רכיב זה מערכת הפלאגינים לא תפעל,' +
                 ' אך שאר האפליקציה תעבוד כרגיל.';
    WV2Color  := $007FFF;  // כתום — אזהרה, לא שגיאה ($BBGGRR: B=00, G=7F, R=FF)
    WV2Check.Checked := True;
    WV2Check.Enabled := True;  // אופציונלי — ניתן לבטל
  end
  else
  begin
    WV2Status := '✓ קיים (גרסה: ' + WV2Version + ') — לא נדרשת פעולה.';
    WV2Color  := $006400;
    WV2Check.Checked := False;
    WV2Check.Enabled := False;  // קיים — נעול כדי למנוע התקנה מיותרת
  end;

  WV2Label := TLabel.Create(CompPage);
  WV2Label.Parent   := CompPage.Surface;
  WV2Label.Left     := ScaleX(20);
  WV2Label.Top      := TopY + ScaleY(18);
  WV2Label.Width    := CompPage.SurfaceWidth - ScaleX(20);
  WV2Label.AutoSize := False;
  WV2Label.WordWrap := True;
  WV2Label.Caption  := WV2Status;
  WV2Label.Font.Color := WV2Color;
  WV2Label.Height   := ScaleY(34);
end;

// ─── דף בחירת תיקיית הספרים ─────────────────────────────────────────────────

procedure UpdateBooksWarning(const Path: String);
begin
  if BooksWarnLabel = nil then exit;
  if DirExists(Path) then
    BooksWarnLabel.Caption :=
      '⚠ שים לב: תיקייה קיימת כבר בנתיב זה.' + #13#10 +
      'התקנה זו תמחק את תוכנה ותחליף בספרים החדשים שבחבילה.'
  else
    BooksWarnLabel.Caption := '';
end;

procedure BrowseBooksFolder(Sender: TObject);
var
  Dir: String;
begin
  Dir := BooksPathEdit.Text;
  if BrowseForFolder('בחר תיקיית ספרים:', Dir, False) then
  begin
    BooksPathEdit.Text := Dir;
    UpdateBooksWarning(Dir);
  end;
end;

procedure CreateBooksPage;
var
  DefaultPath: String;
  DescLabel, PathLabel: TLabel;
begin
  BooksPage := CreateCustomPage(CompPage.ID,
    'תיקיית הספרים',
    'בחר היכן יישמרו ספרי הספרייה');

  DefaultPath := GetDataDir('') + '\books';
  SelectedBooksPath := DefaultPath;

  DescLabel := TLabel.Create(BooksPage);
  DescLabel.Parent   := BooksPage.Surface;
  DescLabel.Left     := 0;
  DescLabel.Top      := 0;
  DescLabel.Width    := BooksPage.SurfaceWidth;
  DescLabel.AutoSize := False;
  DescLabel.WordWrap := True;
  DescLabel.Caption  :=
    'כאן יישמרו קבצי הספרים שמגיעים עם ההתקנה וכל ספר שתוסיף בעתיד.' + #13#10 +
    'הנתיב שתבחר יוגדר אוטומטית בהגדרות התוכנה.';
  DescLabel.Height := ScaleY(42);  // 2 שורות צמודות יותר

  PathLabel := TLabel.Create(BooksPage);
  PathLabel.Parent   := BooksPage.Surface;
  PathLabel.Left     := 0;
  PathLabel.Top      := DescLabel.Height + ScaleY(2);
  PathLabel.Width    := BooksPage.SurfaceWidth;
  PathLabel.AutoSize := False;
  PathLabel.Caption  := 'נתיב תיקיית הספרים:';
  PathLabel.Height   := ScaleY(20);

  BooksPathEdit := TEdit.Create(BooksPage);
  BooksPathEdit.Parent := BooksPage.Surface;
  BooksPathEdit.Left   := 0;
  BooksPathEdit.Top    := PathLabel.Top + ScaleY(26);
  BooksPathEdit.Width  := BooksPage.SurfaceWidth - ScaleX(84);
  BooksPathEdit.Height := ScaleY(22);
  BooksPathEdit.Text   := DefaultPath;

  BooksPathBrowseBtn := TButton.Create(BooksPage);
  BooksPathBrowseBtn.Parent  := BooksPage.Surface;
  BooksPathBrowseBtn.Left    := BooksPage.SurfaceWidth - ScaleX(78);
  BooksPathBrowseBtn.Top     := BooksPathEdit.Top - ScaleY(1);
  BooksPathBrowseBtn.Width   := ScaleX(78);
  BooksPathBrowseBtn.Height  := ScaleY(23);
  BooksPathBrowseBtn.Caption := 'עיון...';
  BooksPathBrowseBtn.OnClick := @BrowseBooksFolder;

  BooksWarnLabel := TLabel.Create(BooksPage);
  BooksWarnLabel.Parent     := BooksPage.Surface;
  BooksWarnLabel.Left       := 0;
  BooksWarnLabel.Top        := BooksPathEdit.Top + BooksPathEdit.Height + ScaleY(8);
  BooksWarnLabel.Width      := BooksPage.SurfaceWidth;
  BooksWarnLabel.AutoSize   := False;
  BooksWarnLabel.WordWrap   := True;
  BooksWarnLabel.Height     := ScaleY(42);
  BooksWarnLabel.Font.Color := clRed;

  UpdateBooksWarning(DefaultPath);
end;

function EscapeJsonString(const Value: String): String;
var
  i: Integer;
begin
  Result := '';
  for i := 1 to Length(Value) do
  begin
    if Value[i] = '\' then
      Result := Result + '\\'
    else if Value[i] = '"' then
      Result := Result + '\"'
    else
      Result := Result + Value[i];
  end;
end;

function LoadTextFile(const FileName: String): String;
var
  Lines: TArrayOfString;
  i: Integer;
begin
  Result := '';
  if not LoadStringsFromFile(FileName, Lines) then
    exit;

  for i := 0 to GetArrayLength(Lines) - 1 do
  begin
    if i > 0 then
      Result := Result + #13#10;
    Result := Result + Lines[i];
  end;
end;

function FindJsonStringEnd(const Text: String; StartPos: Integer): Integer;
begin
  Result := StartPos;
  while Result <= Length(Text) do
  begin
    if (Text[Result] = '"') and ((Result = StartPos) or (Text[Result - 1] <> '\')) then
      exit;
    Result := Result + 1;
  end;

  Result := 0;
end;

// כתיבת נתיב הספרים ל-shared_preferences.json של האפליקציה
procedure WriteLibraryPathToPrefs(const LibraryPath: String);
var
  PrefsDir, PrefsFile, JsonContent, NewEntry: String;
  SharedPrefsKey, LegacyPrefsKey: String;
  KeyPos, ValueStart, ValueEnd, PairEnd, LastBrace, ExistingLength: Integer;
begin
  SharedPrefsKey := '"flutter.key-library-path":';
  LegacyPrefsKey := '"key-library-path":';
  PrefsDir := ExpandConstant('{userappdata}\otzaria');
  PrefsFile := PrefsDir + '\shared_preferences.json';

  ForceDirectories(PrefsDir);

  NewEntry := SharedPrefsKey + '"' + EscapeJsonString(LibraryPath) + '"';

  if FileExists(PrefsFile) then
    JsonContent := Trim(LoadTextFile(PrefsFile))
  else
    JsonContent := '';

  if JsonContent = '' then
  begin
    SaveStringToFile(PrefsFile, '{' + NewEntry + '}', False);
    exit;
  end;

  KeyPos := Pos(SharedPrefsKey, JsonContent);
  ExistingLength := Length(SharedPrefsKey);
  if KeyPos = 0 then
  begin
    KeyPos := Pos(LegacyPrefsKey, JsonContent);
    ExistingLength := Length(LegacyPrefsKey);
  end;

  if KeyPos > 0 then
  begin
    ValueStart := KeyPos + ExistingLength;
    while (ValueStart <= Length(JsonContent)) and (JsonContent[ValueStart] = ' ') do
      ValueStart := ValueStart + 1;

    if (ValueStart <= Length(JsonContent)) and (JsonContent[ValueStart] = '"') then
    begin
      ValueEnd := FindJsonStringEnd(JsonContent, ValueStart + 1);
      if ValueEnd > 0 then
      begin
        PairEnd := ValueEnd + 1;
        while (PairEnd <= Length(JsonContent)) and (JsonContent[PairEnd] = ' ') do
          PairEnd := PairEnd + 1;
        JsonContent :=
          Copy(JsonContent, 1, KeyPos - 1) +
          NewEntry +
          Copy(JsonContent, PairEnd, Length(JsonContent) - PairEnd + 1);
        SaveStringToFile(PrefsFile, JsonContent, False);
        exit;
      end;
    end;
  end;

  LastBrace := Length(JsonContent);
  while (LastBrace > 0) and (JsonContent[LastBrace] <> '}') do
    LastBrace := LastBrace - 1;

  if (LastBrace = 0) or (Trim(JsonContent) = '{}') then
    JsonContent := '{' + NewEntry + '}'
  else
  begin
    PairEnd := LastBrace - 1;
    while (PairEnd > 0) and (JsonContent[PairEnd] <= ' ') do
      PairEnd := PairEnd - 1;

    if (PairEnd > 0) and (JsonContent[PairEnd] <> '{') and (JsonContent[PairEnd] <> ',') then
      JsonContent :=
        Copy(JsonContent, 1, LastBrace - 1) + ',' + NewEntry +
        Copy(JsonContent, LastBrace, Length(JsonContent) - LastBrace + 1)
    else
      JsonContent :=
        Copy(JsonContent, 1, LastBrace - 1) + NewEntry +
        Copy(JsonContent, LastBrace, Length(JsonContent) - LastBrace + 1);
  end;

  SaveStringToFile(PrefsFile, JsonContent, False);
end;

function ShouldInstallWV2: Boolean;
begin
  Result := InstallWV2;
end;

procedure CreateFeaturesPage();
var
  i, col, row: Integer;
  thumbW, thumbH, cellH, x, y, totalH, startY: Integer;
  img: TBitmapImage;
  lbl: TNewStaticText;
  files: array[0..3] of String;
  captions: array[0..3] of String;
begin
  FeaturesPage := CreateCustomPage(wpWelcome,
    'תכונות עיקריות באוצריא',
    'הצצה למה שמחכה לכם בתוכנה');

  files[0] := 'feature1.bmp';  captions[0] := 'ספר עם מפרשים';
  files[1] := 'feature2.bmp';  captions[1] := 'לוח שנה';
  files[2] := 'feature3.bmp';  captions[2] := 'ספרי PDF';
  files[3] := 'feature4.bmp';  captions[3] := 'חיפוש מתקדם';

  // יחס תמונה 210/400. גודל דינמי לפי שטח העמוד.
  thumbW := (FeaturesPage.SurfaceWidth - FEATURES_GAP_X) div 2;
  thumbH := (thumbW * 210) div 400;
  cellH := thumbH + FEATURES_LABEL_H;
  totalH := 2 * cellH + FEATURES_GAP_Y;
  startY := (FeaturesPage.SurfaceHeight - totalH) div 2;
  if startY < 0 then startY := 0;

  for i := 0 to 3 do
  begin
    col := i mod 2;
    row := i div 2;
    x := col * (thumbW + FEATURES_GAP_X);
    y := startY + row * (cellH + FEATURES_GAP_Y);

    ExtractTemporaryFile(files[i]);
    img := TBitmapImage.Create(FeaturesPage);
    img.Parent := FeaturesPage.Surface;
    img.Stretch := True;
    img.Left := x;
    img.Top := y;
    img.Width := thumbW;
    img.Height := thumbH;
    img.Bitmap.LoadFromFile(ExpandConstant('{tmp}\' + files[i]));

    lbl := TNewStaticText.Create(FeaturesPage);
    lbl.Parent := FeaturesPage.Surface;
    lbl.Left := x;
    lbl.Top := y + thumbH + 2;
    lbl.Width := thumbW;
    lbl.Height := FEATURES_LABEL_H;
    lbl.Alignment := taCenter;
    lbl.Caption := captions[i];
  end;
end;

procedure OnSlideshowTimer(H: LongWord; Msg: LongWord; IdEvent: LongWord; Time: LongWord);
var
  NextFile: String;
begin
  if SlideshowImage = nil then
    exit;
  SlideshowIndex := (SlideshowIndex + 1) mod 4;
  case SlideshowIndex of
    0: NextFile := 'feature1.bmp';
    1: NextFile := 'feature2.bmp';
    2: NextFile := 'feature3.bmp';
    3: NextFile := 'feature4.bmp';
  end;
  SlideshowImage.Bitmap.LoadFromFile(ExpandConstant('{tmp}\') + NextFile);
end;

procedure InitializeSlideshow;
var
  GaugeBottom, AvailH, ImgH: Integer;
begin
  SlideshowIndex := 0;
  GaugeBottom := WizardForm.ProgressGauge.Top + WizardForm.ProgressGauge.Height;
  AvailH := WizardForm.InstallingPage.Height - GaugeBottom;
  if AvailH < ScaleY(60) then
    exit;
  ImgH := AvailH - ScaleY(10);

  SlideshowImage := TBitmapImage.Create(WizardForm.InstallingPage);
  SlideshowImage.Parent := WizardForm.InstallingPage;
  SlideshowImage.Stretch := True;
  SlideshowImage.Left := 0;
  SlideshowImage.Top := GaugeBottom + ScaleY(8);
  SlideshowImage.Width := WizardForm.InstallingPage.Width;
  SlideshowImage.Height := ImgH;
  SlideshowImage.Bitmap.LoadFromFile(ExpandConstant('{tmp}\feature1.bmp'));

  SlideshowTimerCallback := CreateCallback(@OnSlideshowTimer);
end;

procedure InitializeWizard;
begin
  InstallWV2 := WebView2NeedsInstall;
  CreateFeaturesPage;
  CreateComponentsPage;
  CreateBooksPage;
  InitializeSlideshow;
end;

procedure CurPageChanged(CurPageID: Integer);
begin
  if SlideshowTimerCallback = 0 then
    exit;
  if CurPageID = wpInstalling then
  begin
    if SlideshowTimerId = 0 then
      SlideshowTimerId := SetTimer(0, 0, 1500, SlideshowTimerCallback);
  end
  else if SlideshowTimerId <> 0 then
  begin
    KillTimer(0, SlideshowTimerId);
    SlideshowTimerId := 0;
  end;
end;

// שמירת בחירות בלחיצת "הבא"
function NextButtonClick(CurPageID: Integer): Boolean;
begin
  Result := True;
  if (CompPage <> nil) and (CurPageID = CompPage.ID) then
  begin
    InstallWV2 := WV2Check.Checked;
  end;
  if (BooksPage <> nil) and (CurPageID = BooksPage.ID) then
  begin
    SelectedBooksPath := BooksPathEdit.Text;
    if SelectedBooksPath = '' then
    begin
      MsgBox('יש לבחור נתיב לתיקיית הספרים.', mbError, MB_OK);
      Result := False;
    end;
  end;
end;

// מריץ קובץ הרצה ולוכד את פלט ה-stderr/stdout שלו, כדי שבמקרה כשל
// נוכל להציג את הודעת השגיאה האמיתית (למשל "אין מקום בדיסק" / "הקובץ נעול")
// במקום קוד יציאה אטום כמו "קוד יציאה: 1".
// מחזיר False רק אם ההרצה עצמה נכשלה; קוד היציאה מוחזר ב-ResultCode.
function RunAndCaptureErrors(const Exe, Params: String;
  var ResultCode: Integer; var CapturedOutput: String): Boolean;
var
  Output: TExecOutput;
  I: Integer;
begin
  CapturedOutput := '';
  Result := ExecAndCaptureOutput(Exe, Params, '', SW_HIDE,
    ewWaitUntilTerminated, ResultCode, Output);
  if not Result then
    exit;
  for I := 0 to GetArrayLength(Output.StdErr) - 1 do
    if Trim(Output.StdErr[I]) <> '' then
      CapturedOutput := CapturedOutput + Output.StdErr[I] + #13#10;
  for I := 0 to GetArrayLength(Output.StdOut) - 1 do
    if Trim(Output.StdOut[I]) <> '' then
      CapturedOutput := CapturedOutput + Output.StdOut[I] + #13#10;
end;

procedure ExtractBundledDatabase(const ArchiveName, DatabaseName: String);
var
  ArchivePath, DatabasePath, ZstdPath, Params, ErrOutput: String;
  ResultCode: Integer;
begin
  ArchivePath := ExpandConstant('{tmp}\' + ArchiveName);
  if not FileExists(ArchivePath) then
  begin
    Log('Bundled database archive not found, skipping: ' + ArchivePath);
    exit;
  end;

  DatabasePath := SelectedBooksPath + '\' + DatabaseName;
  ZstdPath := ExpandConstant('{tmp}\zstd.exe');

  ForceDirectories(ExtractFileDir(DatabasePath));

  Log('Extracting bundled database from ' + ArchivePath);
  Params := '-d -f -T0 --long=31 "' + ArchivePath + '" -o "' + DatabasePath + '"';

  if (not RunAndCaptureErrors(ZstdPath, Params, ResultCode, ErrOutput)) or (ResultCode <> 0) then
  begin
    Log('zstd database extraction failed (' + IntToStr(ResultCode) + '): ' + ErrOutput);
    MsgBox('חילוץ מסד הנתונים נכשל. קוד יציאה: ' + IntToStr(ResultCode)
      + #13#10#13#10 + ErrOutput, mbCriticalError, MB_OK);
    Abort;
  end;

  DeleteFile(ArchivePath);
end;

procedure ExtractBundledTarArchive(const ArchiveName, TargetDirName: String);
var
  ArchivePath, TarPath, ParentDir, TargetDir, ZstdPath, SevenZipPath, Params, ErrOutput: String;
  ResultCode: Integer;
begin
  ArchivePath := ExpandConstant('{tmp}\' + ArchiveName);
  if not FileExists(ArchivePath) then
  begin
    Log('Bundled archive not found, skipping: ' + ArchivePath);
    exit;
  end;

  ParentDir := SelectedBooksPath;
  TarPath := ParentDir + '\' + ChangeFileExt(ArchiveName, '');
  TargetDir := SelectedBooksPath + '\' + TargetDirName;
  ZstdPath := ExpandConstant('{tmp}\zstd.exe');
  SevenZipPath := ExpandConstant('{tmp}\7za.exe');

  if DirExists(TargetDir) then
  begin
    DelTree(TargetDir, True, True, True);
  end;

  Log('Extracting bundled tar archive from ' + ArchivePath);
  Params := '-d -f -T0 --long=31 "' + ArchivePath + '" -o "' + TarPath + '"';

  if (not RunAndCaptureErrors(ZstdPath, Params, ResultCode, ErrOutput)) or (ResultCode <> 0) then
  begin
    Log('zstd PDF archive extraction failed (' + IntToStr(ResultCode) + '): ' + ErrOutput);
    MsgBox('חילוץ ארכיון ה-PDF נכשל. קוד יציאה: ' + IntToStr(ResultCode)
      + #13#10#13#10 + ErrOutput, mbCriticalError, MB_OK);
    Abort;
  end;

  Params := 'x -y "' + TarPath + '" "-o' + ParentDir + '"';
  if (not RunAndCaptureErrors(SevenZipPath, Params, ResultCode, ErrOutput)) or
     (ResultCode <> 0) then
  begin
    Log('7za PDF archive extraction failed (' + IntToStr(ResultCode) + '): ' + ErrOutput);
    MsgBox('פתיחת ארכיון ה-PDF נכשלה. קוד יציאה: ' + IntToStr(ResultCode)
      + #13#10#13#10 + ErrOutput, mbCriticalError, MB_OK);
    Abort;
  end;

  DeleteFile(TarPath);
  DeleteFile(ArchivePath);
  // Optional: Delete the bundled db directory since everything was extracted elsewhere
  // But maybe it's cleaner to handle this in a separate procedure if needed.
end;

// בודק האם הנתיב NewPath כבר נמצא ב-PATH של המשתמש. מחזיר True אם
// יש להוסיף (לא קיים). מטפל גם בגרסה עם backslash סופי. case-insensitive
// כי Windows מתייחס ל-PATH ככזה.
function NeedsAddPath(NewPath: String): Boolean;
var
  CurrentPath: String;
  Needle1, Needle2, Haystack: String;
begin
  Result := True;
  if not RegQueryStringValue(HKCU, 'Environment', 'Path', CurrentPath) then
    exit;

  Haystack  := ';' + Lowercase(CurrentPath) + ';';
  Needle1   := ';' + Lowercase(NewPath) + ';';
  Needle2   := ';' + Lowercase(NewPath) + '\;';
  if (Pos(Needle1, Haystack) > 0) or (Pos(Needle2, Haystack) > 0) then
    Result := False;
end;

// מסיר את PathToRemove מ-PATH של המשתמש (ב-uninstall). מטפל בשני
// הוריאנטים — עם וללא backslash סופי — **בנפרד**, כדי שכפילות
// היסטורית (גם 'C:\app' וגם 'C:\app\') תוסר במלואה. גם מסיר כל
// מופע חוזר.
procedure RemoveAppFromUserPath(PathToRemove: String);
var
  CurrentPath, LowerCurrent: String;
  Needles: array[0..1] of String;
  LowerNeedle: String;
  P, i: Integer;
  Changed: Boolean;
begin
  if not RegQueryStringValue(HKCU, 'Environment', 'Path', CurrentPath) then
    exit;

  Changed := False;
  CurrentPath := ';' + CurrentPath + ';';

  Needles[0] := ';' + Lowercase(PathToRemove) + ';';
  Needles[1] := ';' + Lowercase(PathToRemove) + '\;';

  for i := 0 to 1 do
  begin
    LowerNeedle := Needles[i];
    LowerCurrent := Lowercase(CurrentPath);
    P := Pos(LowerNeedle, LowerCurrent);
    while P > 0 do
    begin
      Delete(CurrentPath, P, Length(LowerNeedle) - 1);
      LowerCurrent := Lowercase(CurrentPath);
      Changed := True;
      P := Pos(LowerNeedle, LowerCurrent);
    end;
  end;

  if not Changed then
    exit;

  if (Length(CurrentPath) > 0) and (CurrentPath[1] = ';') then
    Delete(CurrentPath, 1, 1);
  if (Length(CurrentPath) > 0) and (CurrentPath[Length(CurrentPath)] = ';') then
    Delete(CurrentPath, Length(CurrentPath), 1);

  RegWriteExpandStringValue(HKCU, 'Environment', 'Path', CurrentPath);
end;

// מחזיר את נתיב תיקיית הספרים שהמשתמש בחר (אם שונה מברירת המחדל),
// כפי שנשמר ב-shared_preferences.json תחת המפתח flutter.key-library-path.
// משתמש בעוזרי ה-JSON הקיימים (LoadTextFile, FindJsonStringEnd) ובפענוח
// escapes ה-JSON בסיסי שתואם ל-EscapeJsonString.
function GetCustomLibraryPath(): String;
var
  PrefsFile, JsonContent, KeyStr, Value: String;
  KeyPos, ValueStart, ValueEnd: Integer;
begin
  Result := '';
  PrefsFile := ExpandConstant('{userappdata}\otzaria\shared_preferences.json');
  if not FileExists(PrefsFile) then
    exit;

  JsonContent := LoadTextFile(PrefsFile);
  if JsonContent = '' then
    exit;

  KeyStr := '"flutter.key-library-path":';
  KeyPos := Pos(KeyStr, JsonContent);
  if KeyPos = 0 then
  begin
    KeyStr := '"key-library-path":';
    KeyPos := Pos(KeyStr, JsonContent);
  end;
  if KeyPos = 0 then
    exit;

  ValueStart := KeyPos + Length(KeyStr);
  while (ValueStart <= Length(JsonContent)) and
        (JsonContent[ValueStart] <> '"') do
    ValueStart := ValueStart + 1;
  if ValueStart > Length(JsonContent) then
    exit;
  ValueStart := ValueStart + 1;

  ValueEnd := FindJsonStringEnd(JsonContent, ValueStart);
  if ValueEnd <= 0 then
    exit;

  Value := Copy(JsonContent, ValueStart, ValueEnd - ValueStart);
  StringChangeEx(Value, '\\', '\', True);
  StringChangeEx(Value, '\"', '"', True);
  Result := Value;
end;

// בודק שהתיקייה נראית כמו תיקיית ספרים של אוצריא — כלומר מכילה לפחות
// אחד מהסימנים הייחודיים שמותקנים ע"י המתקין FULL. נחוץ לפני DelTree על
// נתיב שמגיע מהמשתמש (prefs), כדי שלא נמחק תיקייה אישית רחבה שהמשתמש
// בחר בטעות כנתיב ספרים (למשל D:\, Downloads, Documents).
function IsOtzariaBooksFolder(const Path: String): Boolean;
begin
  Result := False;
  // אורך מינימלי 6 פוסל גם 'C:\' וגם 'C:\X'; מונע מחיקה בקרבת שורש כונן.
  if (Path = '') or (Length(Path) < 6) then
    exit;
  if not DirExists(Path) then
    exit;
  if FileExists(Path + '\seforim.db') or
     FileExists(Path + '\otzar-HB_catalog.db') or
     DirExists(Path + '\תלמוד בבלי') then
    Result := True;
end;

// מוחק את כל הנתונים והספרים של אוצריא: ספריית הספרים המותאמת אישית
// (רק אם היא מזוהה כתיקיית אוצריא — ראה IsOtzariaBooksFolder), כל תיקיות
// הנתונים הסטנדרטיות וגם נתיבי legacy. קוראים את הנתיב המותאם מה-prefs
// לפני שמוחקים את ה-prefs עצמו.
procedure DeleteAllUserData();
var
  Path: String;
begin
  Path := GetCustomLibraryPath();
  if IsOtzariaBooksFolder(Path) then
    DelTree(Path, True, True, True);

  Path := ExpandConstant('{commonappdata}\otzaria');
  if DirExists(Path) then
    DelTree(Path, True, True, True);

  Path := ExpandConstant('{userappdata}\otzaria');
  if DirExists(Path) then
    DelTree(Path, True, True, True);

  Path := ExpandConstant('{localappdata}\otzaria');
  if DirExists(Path) then
    DelTree(Path, True, True, True);

  // com.example הוא מזהה ברירת המחדל של Flutter — מוחקים רק את תת-תיקיית
  // otzaria, אחרת נמחקים נתונים של אפליקציות Flutter אחרות.
  Path := ExpandConstant('{userappdata}\com.example\otzaria');
  if DirExists(Path) then
    DelTree(Path, True, True, True);

  Path := ExpandConstant('{localappdata}\אוצריא');
  if DirExists(Path) then
    DelTree(Path, True, True, True);

  // הערה: C:\אוצריא לא נמחק כאן כי זה היה נתיב התקנה legacy (לא נתונים).
  // אם נשארה שם התקנה ישנה — היא תוסר על ידי ה-uninstaller שלה.
end;

// שאלה בתחילת ההסרה: האם למחוק גם את הנתונים והספרים?
// בהסרה שקטה (כולל עדכון שמריץ unins000.exe /SILENT) MsgBox מחזיר אוטומטית
// את ברירת המחדל; MB_DEFBUTTON2 דואג שברירת המחדל היא "לא" כך שנתוני
// המשתמש נשמרים אם הוא לא בחר במפורש למחוק.
function InitializeUninstall(): Boolean;
var
  CustomPath, Msg: String;
begin
  Result := True;
  DeleteUserDataOnUninstall := False;

  CustomPath := GetCustomLibraryPath();

  Msg := 'האם למחוק גם את הספרים וכל הנתונים של אוצריא?' + #13#10 + #13#10 +
         'בכל מקרה תוסר התוכנה. בחירה ב"כן" תמחק בנוסף:' + #13#10;

  // אם יש נתיב ספרים מותאם והוא מזוהה כתיקיית אוצריא — נציג אותו במפורש.
  // אחרת לא מציינים נתיב חיצוני; תיקיית הספרים שתחת AppData ממילא נמחקת
  // כחלק מ-{userappdata}\otzaria / {commonappdata}\otzaria.
  if IsOtzariaBooksFolder(CustomPath) then
    Msg := Msg + '• תיקיית הספרים:' + #13#10 +
                 '   ' + CustomPath + #13#10
  else
    Msg := Msg + '• תיקיית הספרים שתחת תיקיית הנתונים' + #13#10;

  Msg := Msg +
         '• מסדי הנתונים, אינדקס החיפוש, הגדרות,' + #13#10 +
         '   סימניות, היסטוריה והערות אישיות' + #13#10 + #13#10 +
         'בחר "לא" כדי לשמור את הנתונים לקראת התקנה עתידית.';

  if MsgBox(Msg, mbConfirmation, MB_YESNO or MB_DEFBUTTON2) = IDYES then
  begin
    if MsgBox(
         'שים לב: לא ניתן יהיה לשחזר את הנתונים לאחר המחיקה.' + #13#10 + #13#10 +
         'האם אתה בטוח שברצונך למחוק את כל הספרים והנתונים?',
         mbCriticalError, MB_YESNO or MB_DEFBUTTON2) = IDYES then
      DeleteUserDataOnUninstall := True;
  end;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  if CurUninstallStep = usPostUninstall then
  begin
    RemoveAppFromUserPath(ExpandConstant('{app}'));
    if DeleteUserDataOnUninstall then
      DeleteAllUserData();
  end;
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  ZstdPath, SevenZipPath: String;
  AppDataPath: string;
  ErrorLogPath: string;
begin
  if CurStep = ssInstall then
  begin
    // מחק את לוג השגיאות הישן בכל התקנה/עדכון
    ErrorLogPath := ExpandConstant('{userappdata}\otzaria\logs\errors.txt');
    if FileExists(ErrorLogPath) then
      DeleteFile(ErrorLogPath);
    ErrorLogPath := ExpandConstant('{commonappdata}\otzaria\logs\errors.txt');
    if FileExists(ErrorLogPath) then
      DeleteFile(ErrorLogPath);

    if WizardIsTaskSelected('resetsettings') then
    begin
      AppDataPath := GetDataDir('');
      if DirExists(AppDataPath) then
        DelTreeExceptBackups(AppDataPath);

      AppDataPath := ExpandConstant('{userappdata}\otzaria');
      if DirExists(AppDataPath) then
        DelTreeExceptBackups(AppDataPath);

      AppDataPath := ExpandConstant('{commonappdata}\otzaria');
      if DirExists(AppDataPath) then
        DelTreeExceptBackups(AppDataPath);

      AppDataPath := ExpandConstant('{localappdata}\otzaria');
      if DirExists(AppDataPath) then
        DelTreeExceptBackups(AppDataPath);

      // com.example הוא מזהה ברירת המחדל של Flutter — רק תת-תיקיית otzaria
      // שייכת לנו; מחיקת כל com.example תמחק נתונים של אפליקציות אחרות.
      AppDataPath := ExpandConstant('{userappdata}\com.example\otzaria');
      if DirExists(AppDataPath) then
        DelTreeExceptBackups(AppDataPath);

      // נתיבים ישנים מאוד: LocalAppData בעברית (לפני גרסה 0.9.x)
      AppDataPath := ExpandConstant('{localappdata}\אוצריא');
      if DirExists(AppDataPath) then
        DelTree(AppDataPath, True, True, True);

      AppDataPath := ExpandConstant('{localappdata}\אוצריא\Data');
      if DirExists(AppDataPath) then
        DelTree(AppDataPath, True, True, True);
    end;
  end;

  if CurStep <> ssPostInstall then
    exit;

  ZstdPath := ExpandConstant('{tmp}\zstd.exe');
  SevenZipPath := ExpandConstant('{tmp}\7za.exe');

  if not FileExists(ZstdPath) then
  begin
    MsgBox('קובץ החילוץ zstd.exe לא נמצא. ההתקנה לא יכולה לחלץ את קבצי הספרייה המצורפים.', mbCriticalError, MB_OK);
    Abort;
  end;

  if not FileExists(SevenZipPath) then
  begin
    MsgBox('קובץ החילוץ 7za.exe לא נמצא. ההתקנה לא יכולה לחלץ את קבצי ה-PDF המצורפים.', mbCriticalError, MB_OK);
    Abort;
  end;

  WizardForm.ProgressGauge.Style := npbstMarquee;

  WizardForm.StatusLabel.Caption := 'מחלץ מסד הנתונים seforim.db...';
  WizardForm.StatusLabel.Update;
  ExtractBundledDatabase('seforim.db.zst', 'seforim.db');

  WizardForm.StatusLabel.Caption := 'מחלץ קטלוג אוצר החכמה...';
  WizardForm.StatusLabel.Update;
  ExtractBundledDatabase('otzar-HB_catalog.db.zst', 'otzar-HB_catalog.db');

  WizardForm.StatusLabel.Caption := 'מחלץ ספרי תלמוד בבלי...';
  WizardForm.StatusLabel.Update;
  ExtractBundledTarArchive('talmud_bavli_latest.tar.zst', 'תלמוד בבלי');

  WizardForm.StatusLabel.Caption := 'מחלץ מילון לחיפוש המקורב...';
  WizardForm.StatusLabel.Update;
  ExtractBundledDatabase('lexical.db.zst', 'lexical.db');

  WizardForm.ProgressGauge.Style := npbstNormal;
  WizardForm.ProgressGauge.Position := WizardForm.ProgressGauge.Max;

  // יצירת תיקיית הספרים בנתיב שבחר המשתמש (אם שונה מברירת המחדל)
  if SelectedBooksPath <> '' then
  begin
    ForceDirectories(SelectedBooksPath);
    WriteLibraryPathToPrefs(SelectedBooksPath);
  end;
end;

[Run]
; Visual C++ Redistributable כבר לא מותקן ע"י המתקין — ה-DLLs של ה-runtime
; נארזים app-local ליד otzaria.exe (ראה .github/workflows/build-and-announce.yml,
; השלב "Bundle latest VC++ Redistributable runtime DLLs"). זה פותר גם משתמשים
; שתקועים עם MSVCP140.dll 14.36.32532.0 הפגום, בלי הרצת installer נוסף.
Filename: "{tmp}\MicrosoftEdgeWebview2Setup.exe"; Parameters: "/silent /install"; StatusMsg: "מתקין Microsoft WebView2 Runtime..."; Flags: waituntilterminated; Check: ShouldInstallWV2
Filename: "{app}\{#MyAppExeName}"; Description: "הפעל את {#MyAppName}"; Flags: nowait postinstall skipifsilent

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; AppUserModelID: "Otzaria.Otzaria"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon; AppUserModelID: "Otzaria.Otzaria"
; קיצור דרך ישיר ללוח השנה — מעביר ל-otzaria.exe deep link כפרמטר; אוצריא מזהה
; ארגומנט שמתחיל ב-"otzaria:" וממסרת לראוטר הפנימי (ראה docs/deep_links.md לזרימה המלאה).
; AppUserModelID זהה לסמל הראשי כדי שהקיצור יתאחד עם הכפתור המוצמד בשורת המשימות.
Name: "{autodesktop}\לוח שנה - {#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Parameters: "otzaria://open/calendar"; Tasks: calendaricon; AppUserModelID: "Otzaria.Otzaria"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "calendaricon"; Description: "צור קיצור דרך ישירות ללוח שנה"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "resetsettings"; Description: "איפוס הגדרות משתמש והסרת התקנות קודמות (מומלץ למעדכנים מגרסה < 0.9.80, שים לב: זה ימחק הערות אישיות, סימניות, היסטוריה ונתוני תוספים! תיקיית הגיבויים נשמרת)"; Flags: unchecked
Name: "addtopath"; Description: "הוסף את אוצריא ל-PATH של המשתמש (יאפשר להריץ ‎`otzaria pack-plugin`‎ ישירות מהטרמינל)"; Flags: unchecked

[Files]
; Copy DLL files without compression to prevent corruption
Source: "..\build\windows\x64\runner\Release\*.dll"; DestDir: "{app}"; Flags: ignoreversion nocompression
; Copy all other app files
Source: "..\build\windows\x64\runner\Release\*"; \
  Excludes: "*.dll"; \
    DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

; Compressed library assets + extraction tools staged in the setup temp dir —
; {tmp} is always writable by the installer process (unlike {app} under Program Files)
; and is auto-deleted when setup exits, even on abort
Source: "library_db\seforim.db.zst"; DestDir: "{tmp}"; Flags: deleteafterinstall nocompression
Source: "library_db\otzar-HB_catalog.db.zst"; DestDir: "{tmp}"; Flags: deleteafterinstall nocompression
Source: "library_db\talmud_bavli_latest.tar.zst"; DestDir: "{tmp}"; Flags: deleteafterinstall nocompression
Source: "library_db\lexical.db.zst"; DestDir: "{tmp}"; Flags: deleteafterinstall nocompression
Source: "zstd.exe"; DestDir: "{tmp}"; Flags: deleteafterinstall
Source: "7za.exe"; DestDir: "{tmp}"; Flags: deleteafterinstall

; MicrosoftEdgeWebview2Setup.exe — bootstrapper קטן (~2MB) שמוריד ומתקין WebView2
; נדרש על ידי flutter_inappwebview_windows; ב-Win10/11 עם Edge עדכני — כבר קיים
Source: "MicrosoftEdgeWebview2Setup.exe"; DestDir: "{tmp}"; Flags: deleteafterinstall; Check: ShouldInstallWV2

; קבצי הצגה לדף "תכונות עיקריות" - dontcopy = נארזים בתוך המתקין אבל לא מותקנים אצל המשתמש
Source: "feature1.bmp"; Flags: dontcopy
Source: "feature2.bmp"; Flags: dontcopy
Source: "feature3.bmp"; Flags: dontcopy
Source: "feature4.bmp"; Flags: dontcopy

[INI]
Filename: "{app}\system_install.marker"; Section: "Install"; Key: "Mode"; String: "Admin"; Check: IsAdminInstallMode
