; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "אוצריא"
#define MyAppVersion "0.9.91"
#define MyAppPublisher "sivan22"
#define MyAppURL "https://github.com/otzaria/otzaria"
#define MyAppExeName "otzaria.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{EEC4F712-CD05-4D15-A753-509E840A51A5}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
DefaultDirName={code:GetDefaultInstallDir}
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
OutputDir=.
OutputBaseFilename=otzaria-{#MyAppVersion}-windows-full
SetupIconFile=white_sketch128x128.ico
Compression=lzma
SolidCompression=yes
; Disable compression for DLL files to prevent corruption
CompressionThreads=1
WizardStyle=modern
DisableDirPage=no

[InstallDelete]
; מחיקת ספריית נתונים ישנה לפני פריסת מסד הנתונים החדש
Type: filesandordirs; Name: "{code:GetSelectedBooksPath}"

[Dirs]
Name: "{code:GetDataDir}"; Permissions: users-modify
Name: "{code:GetDataDir}\books"; Permissions: users-modify
Name: "{code:GetDataDir}\index"; Permissions: users-modify

[Registry]
Root: HKA; Subkey: "Software\Classes\otzaria"; ValueType: string; ValueName: ""; ValueData: "URL:Otzaria Protocol"; Flags: uninsdeletekeyifempty
Root: HKA; Subkey: "Software\Classes\otzaria"; ValueType: string; ValueName: "URL Protocol"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\otzaria\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName}"; Flags: uninsdeletekeyifempty
Root: HKA; Subkey: "Software\Classes\otzaria\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""; Flags: uninsdeletekeyifempty

[Languages]
Name: "hebrew"; MessagesFile: "compiler:Languages\Hebrew.isl"

[Code]

var
  CompPage: TWizardPage;
  VCCheck, WV2Check: TCheckBox;
  VCLabel, WV2Label: TLabel;
  InstallVC, InstallWV2: Boolean;

  BooksPage: TWizardPage;
  BooksPathEdit: TEdit;
  BooksPathBrowseBtn: TButton;
  SelectedBooksPath: String;

function TryGetInstallDirFromRegistry(RootKey: Integer; const SubKey: String; var InstallDir: String): Boolean;
begin
  Result := RegQueryStringValue(RootKey, SubKey, 'Inno Setup: App Path', InstallDir);
  if (not Result) or (InstallDir = '') then
    Result := RegQueryStringValue(RootKey, SubKey, 'InstallLocation', InstallDir);

  if Result and DirExists(InstallDir) then
    exit;

  InstallDir := '';
  Result := False;
end;

function FindPreviousInstallDir(): String;
var
  InstallDir: String;
  LegacyDir: String;
  UninstallKey: String;
begin
  UninstallKey := 'Software\Microsoft\Windows\CurrentVersion\Uninstall\{EEC4F712-CD05-4D15-A753-509E840A51A5}_is1';

  if TryGetInstallDirFromRegistry(HKLM64, UninstallKey, InstallDir) or
     TryGetInstallDirFromRegistry(HKCU, UninstallKey, InstallDir) then
  begin
    Result := InstallDir;
    exit;
  end;

  LegacyDir := 'C:\אוצריא';
  if DirExists(LegacyDir) then
  begin
    Result := LegacyDir;
    exit;
  end;

  LegacyDir := ExpandConstant('{autopf}\אוצריא');
  if DirExists(LegacyDir) then
  begin
    Result := LegacyDir;
    exit;
  end;

  LegacyDir := ExpandConstant('{autopf}\Otzaria');
  if DirExists(LegacyDir) then
  begin
    Result := LegacyDir;
    exit;
  end;

  Result := '';
end;

function GetDefaultInstallDir(Param: String): String;
begin
  Result := FindPreviousInstallDir();
  if Result = '' then
    Result := ExpandConstant('{autopf}\אוצריא');
end;

function GetDataDir(Param: String): String;
begin
  if IsAdminInstallMode then
    Result := ExpandConstant('{commonappdata}\otzaria')
  else
    Result := ExpandConstant('{userappdata}\otzaria');
end;

function GetSelectedBooksPath(Param: String): String;
begin
  if SelectedBooksPath <> '' then
    Result := SelectedBooksPath
  else
    Result := GetDataDir('') + '\books';
end;

// ─── בדיקות רכיבי מערכת ───────────────────────────────────────────────────

function GetVCVersion: String;
var
  Version: String;
begin
  if RegQueryStringValue(HKLM64,
      'SOFTWARE\Microsoft\VisualStudio\14.0\VC\Runtimes\x64',
      'Version', Version) then
    Result := Version
  else
    Result := '';
end;

function GetWebView2Version: String;
var
  Version: String;
begin
  if RegQueryStringValue(HKLM64,
      'SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}',
      'pv', Version) then
  begin
    Result := Version;
    exit;
  end;
  if RegQueryStringValue(HKCU,
      'SOFTWARE\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}',
      'pv', Version) then
    Result := Version
  else
    Result := '';
end;

function VCRedistNeedsInstall: Boolean;
begin
  Result := GetVCVersion = '';
end;

function WebView2NeedsInstall: Boolean;
begin
  Result := GetWebView2Version = '';
end;

function InitializeSetup(): Boolean;
var
  DataPath, OldPath: String;
begin
  Result := True;
  DataPath := GetDataDir('');
  OldPath := 'C:\אוצריא';

  // בדיקה אם יש התקנה ישנה בנתיב העברי
  if DirExists(OldPath) then
  begin
    if MsgBox('נמצאה התקנה ישנה ב-' + OldPath + #13#10 +
              'ספריית הספרים עוברת לנתיב חדש: ' + DataPath + #13#10#13#10 +
              'האם להעביר את הנתונים למיקום החדש?',
              mbConfirmation, MB_YESNO) = IDYES then
    begin
      // המשתמש יצטרך להעביר ידנית או שנוסיף קוד העברה
      MsgBox('לאחר ההתקנה, תוכל להעביר את הנתונים מ-' + OldPath + ' ל-' + DataPath, mbInformation, MB_OK);
    end;
  end;

  // האזהרה על מחיקת ספרים קיימים מוצגת בדף בחירת תיקיית הספרים

  // אתחול ברירות מחדל — גם להתקנה שקטה (/SILENT, /VERYSILENT)
  InstallVC  := VCRedistNeedsInstall;
  InstallWV2 := WebView2NeedsInstall;
  SelectedBooksPath := GetDataDir('') + '\books';
end;

// ─── בניית עמוד בחירת רכיבים ───────────────────────────────────────────────

procedure CreateComponentsPage;
var
  VCVersion, WV2Version: String;
  VCStatus, WV2Status: String;
  VCColor, WV2Color: TColor;
  TopY: Integer;
  HeaderLabel: TLabel;
begin
  CompPage := CreateCustomPage(wpSelectDir,
    'בחירת רכיבי מערכת להתקנה',
    'בדיקת הרכיבים הנדרשים לאפליקציה');

  VCVersion  := GetVCVersion;
  WV2Version := GetWebView2Version;

  // כותרת הסבר
  HeaderLabel := TLabel.Create(CompPage);
  HeaderLabel.Parent := CompPage.Surface;
  HeaderLabel.Left   := 0;
  HeaderLabel.Top    := 0;
  HeaderLabel.Width  := CompPage.SurfaceWidth;
  HeaderLabel.AutoSize := False;
  HeaderLabel.WordWrap := True;
  HeaderLabel.Caption :=
    'להלן רכיבי המערכת הנדרשים לפעולת אוצריא.' + #13#10 +
    'רכיבים באדום חסרים — נדרשת התקנה.' + #13#10 +
    'רכיבים ירוקים קיימים — אין צורך בפעולה.';
  HeaderLabel.Height := ScaleY(60);  // 3 שורות קצרות, בלי עודף ריפוד

  TopY := HeaderLabel.Height + ScaleY(6);

  // ─── Visual C++ Runtime ───────────────────────────────────────────────────
  VCCheck := TCheckBox.Create(CompPage);
  VCCheck.Parent  := CompPage.Surface;
  VCCheck.Left    := 0;
  VCCheck.Top     := TopY + ScaleY(2);
  VCCheck.Width   := CompPage.SurfaceWidth;
  VCCheck.Height  := ScaleY(20);
  VCCheck.Caption := 'Visual C++ Redistributable 2022 (x64)';

  if VCVersion = '' then
  begin
    VCStatus := '⚠ חסר — נדרשת התקנה! ללא רכיב זה האפליקציה לא תפעל.';
    VCColor  := clRed;
    VCCheck.Checked := True;
    VCCheck.Enabled := False;  // חובה — לא ניתן לבטל
  end
  else
  begin
    VCStatus := '✓ קיים (גרסה: ' + VCVersion + ') — לא נדרשת פעולה.';
    VCColor  := $006400;  // ירוק כהה
    VCCheck.Checked := False;
    VCCheck.Enabled := False;  // קיים — נעול כדי למנוע התקנה מיותרת
  end;

  VCLabel := TLabel.Create(CompPage);
  VCLabel.Parent   := CompPage.Surface;
  VCLabel.Left     := ScaleX(20);
  VCLabel.Top      := TopY + ScaleY(18);
  VCLabel.Width    := CompPage.SurfaceWidth - ScaleX(20);
  VCLabel.AutoSize := False;
  VCLabel.WordWrap := True;
  VCLabel.Caption  := VCStatus;
  VCLabel.Font.Color := VCColor;
  VCLabel.Height   := ScaleY(36);

  TopY := TopY + ScaleY(58);

  // ─── WebView2 Runtime ─────────────────────────────────────────────────────
  WV2Check := TCheckBox.Create(CompPage);
  WV2Check.Parent  := CompPage.Surface;
  WV2Check.Left    := 0;
  WV2Check.Top     := TopY;
  WV2Check.Width   := CompPage.SurfaceWidth;
  WV2Check.Height  := ScaleY(20);
  WV2Check.Caption := 'Microsoft WebView2 Runtime';

  // WebView2 אינו חובה — משמש רק למערכת הפלאגינים (לא לקריאה/חיפוש/סימניות)
  if WV2Version = '' then
  begin
    WV2Status := '⚠ חסר — מומלץ להתקין. ללא רכיב זה מערכת הפלאגינים לא תפעל,' +
                 ' אך שאר האפליקציה תעבוד כרגיל.';
    WV2Color  := $007FFF;  // כתום — אזהרה, לא שגיאה ($BBGGRR: B=00, G=7F, R=FF)
    WV2Check.Checked := True;
    WV2Check.Enabled := True;  // אופציונלי — ניתן לבטל
  end
  else
  begin
    WV2Status := '✓ קיים (גרסה: ' + WV2Version + ') — לא נדרשת פעולה.';
    WV2Color  := $006400;
    WV2Check.Checked := False;
    WV2Check.Enabled := False;  // קיים — נעול כדי למנוע התקנה מיותרת
  end;

  WV2Label := TLabel.Create(CompPage);
  WV2Label.Parent   := CompPage.Surface;
  WV2Label.Left     := ScaleX(20);
  WV2Label.Top      := TopY + ScaleY(18);
  WV2Label.Width    := CompPage.SurfaceWidth - ScaleX(20);
  WV2Label.AutoSize := False;
  WV2Label.WordWrap := True;
  WV2Label.Caption  := WV2Status;
  WV2Label.Font.Color := WV2Color;
  WV2Label.Height   := ScaleY(34);
end;

// ─── דף בחירת תיקיית הספרים ─────────────────────────────────────────────────

procedure BrowseBooksFolder(Sender: TObject);
var
  Dir: String;
begin
  Dir := BooksPathEdit.Text;
  if BrowseForFolder('בחר תיקיית ספרים:', Dir, False) then
    BooksPathEdit.Text := Dir;
end;

procedure CreateBooksPage;
var
  DefaultPath: String;
  DescLabel, WarnLabel, PathLabel: TLabel;
begin
  BooksPage := CreateCustomPage(CompPage.ID,
    'תיקיית הספרים',
    'בחר היכן יישמרו ספרי הספרייה');

  DefaultPath := GetDataDir('') + '\books';
  SelectedBooksPath := DefaultPath;

  DescLabel := TLabel.Create(BooksPage);
  DescLabel.Parent   := BooksPage.Surface;
  DescLabel.Left     := 0;
  DescLabel.Top      := 0;
  DescLabel.Width    := BooksPage.SurfaceWidth;
  DescLabel.AutoSize := False;
  DescLabel.WordWrap := True;
  DescLabel.Caption  :=
    'כאן יישמרו קבצי הספרים שמגיעים עם ההתקנה וכל ספר שתוסיף בעתיד.' + #13#10 +
    'הנתיב שתבחר יוגדר אוטומטית בהגדרות התוכנה.';
  DescLabel.Height := ScaleY(42);  // 2 שורות צמודות יותר

  PathLabel := TLabel.Create(BooksPage);
  PathLabel.Parent   := BooksPage.Surface;
  PathLabel.Left     := 0;
  PathLabel.Top      := DescLabel.Height + ScaleY(2);
  PathLabel.Width    := BooksPage.SurfaceWidth;
  PathLabel.AutoSize := False;
  PathLabel.Caption  := 'נתיב תיקיית הספרים:';
  PathLabel.Height   := ScaleY(20);

  BooksPathEdit := TEdit.Create(BooksPage);
  BooksPathEdit.Parent := BooksPage.Surface;
  BooksPathEdit.Left   := 0;
  BooksPathEdit.Top    := PathLabel.Top + ScaleY(26);
  BooksPathEdit.Width  := BooksPage.SurfaceWidth - ScaleX(84);
  BooksPathEdit.Height := ScaleY(22);
  BooksPathEdit.Text   := DefaultPath;

  BooksPathBrowseBtn := TButton.Create(BooksPage);
  BooksPathBrowseBtn.Parent  := BooksPage.Surface;
  BooksPathBrowseBtn.Left    := BooksPage.SurfaceWidth - ScaleX(78);
  BooksPathBrowseBtn.Top     := BooksPathEdit.Top - ScaleY(1);
  BooksPathBrowseBtn.Width   := ScaleX(78);
  BooksPathBrowseBtn.Height  := ScaleY(23);
  BooksPathBrowseBtn.Caption := 'עיון...';
  BooksPathBrowseBtn.OnClick := @BrowseBooksFolder;

  WarnLabel := TLabel.Create(BooksPage);
  WarnLabel.Parent     := BooksPage.Surface;
  WarnLabel.Left       := 0;
  WarnLabel.Top        := BooksPathEdit.Top + BooksPathEdit.Height + ScaleY(8);
  WarnLabel.Width      := BooksPage.SurfaceWidth;
  WarnLabel.AutoSize   := False;
  WarnLabel.WordWrap   := True;
  WarnLabel.Height     := ScaleY(42);
  WarnLabel.Font.Color := clRed;

  if DirExists(DefaultPath) then
    WarnLabel.Caption :=
      '⚠ שים לב: תיקיית ספרים קיימת כבר בנתיב זה.' + #13#10 +
      'התקנה זו תמחק את תוכנה ותחליף בספרים החדשים שבחבילה.'
  else
    WarnLabel.Caption := '';
end;

function EscapeJsonString(const Value: String): String;
var
  i: Integer;
begin
  Result := '';
  for i := 1 to Length(Value) do
  begin
    if Value[i] = '\' then
      Result := Result + '\\'
    else if Value[i] = '"' then
      Result := Result + '\"'
    else
      Result := Result + Value[i];
  end;
end;

function LoadTextFile(const FileName: String): String;
var
  Lines: TArrayOfString;
  i: Integer;
begin
  Result := '';
  if not LoadStringsFromFile(FileName, Lines) then
    exit;

  for i := 0 to GetArrayLength(Lines) - 1 do
  begin
    if i > 0 then
      Result := Result + #13#10;
    Result := Result + Lines[i];
  end;
end;

function FindJsonStringEnd(const Text: String; StartPos: Integer): Integer;
begin
  Result := StartPos;
  while Result <= Length(Text) do
  begin
    if (Text[Result] = '"') and ((Result = StartPos) or (Text[Result - 1] <> '\')) then
      exit;
    Result := Result + 1;
  end;

  Result := 0;
end;

// כתיבת נתיב הספרים ל-shared_preferences.json של האפליקציה
procedure WriteLibraryPathToPrefs(const LibraryPath: String);
var
  PrefsDir, PrefsFile, JsonContent, NewEntry: String;
  SharedPrefsKey, LegacyPrefsKey: String;
  KeyPos, ValueStart, ValueEnd, PairEnd, LastBrace, ExistingLength: Integer;
begin
  SharedPrefsKey := '"flutter.key-library-path":';
  LegacyPrefsKey := '"key-library-path":';
  PrefsDir := ExpandConstant('{userappdata}\otzaria');
  PrefsFile := PrefsDir + '\shared_preferences.json';

  ForceDirectories(PrefsDir);

  NewEntry := SharedPrefsKey + '"' + EscapeJsonString(LibraryPath) + '"';

  if FileExists(PrefsFile) then
    JsonContent := Trim(LoadTextFile(PrefsFile))
  else
    JsonContent := '';

  if JsonContent = '' then
  begin
    SaveStringToFile(PrefsFile, '{' + NewEntry + '}', False);
    exit;
  end;

  KeyPos := Pos(SharedPrefsKey, JsonContent);
  ExistingLength := Length(SharedPrefsKey);
  if KeyPos = 0 then
  begin
    KeyPos := Pos(LegacyPrefsKey, JsonContent);
    ExistingLength := Length(LegacyPrefsKey);
  end;

  if KeyPos > 0 then
  begin
    ValueStart := KeyPos + ExistingLength;
    while (ValueStart <= Length(JsonContent)) and (JsonContent[ValueStart] = ' ') do
      ValueStart := ValueStart + 1;

    if (ValueStart <= Length(JsonContent)) and (JsonContent[ValueStart] = '"') then
    begin
      ValueEnd := FindJsonStringEnd(JsonContent, ValueStart + 1);
      if ValueEnd > 0 then
      begin
        PairEnd := ValueEnd + 1;
        while (PairEnd <= Length(JsonContent)) and (JsonContent[PairEnd] = ' ') do
          PairEnd := PairEnd + 1;
        JsonContent :=
          Copy(JsonContent, 1, KeyPos - 1) +
          NewEntry +
          Copy(JsonContent, PairEnd, Length(JsonContent) - PairEnd + 1);
        SaveStringToFile(PrefsFile, JsonContent, False);
        exit;
      end;
    end;
  end;

  LastBrace := Length(JsonContent);
  while (LastBrace > 0) and (JsonContent[LastBrace] <> '}') do
    LastBrace := LastBrace - 1;

  if (LastBrace = 0) or (Trim(JsonContent) = '{}') then
    JsonContent := '{' + NewEntry + '}'
  else
  begin
    PairEnd := LastBrace - 1;
    while (PairEnd > 0) and (JsonContent[PairEnd] <= ' ') do
      PairEnd := PairEnd - 1;

    if (PairEnd > 0) and (JsonContent[PairEnd] <> '{') and (JsonContent[PairEnd] <> ',') then
      JsonContent :=
        Copy(JsonContent, 1, LastBrace - 1) + ',' + NewEntry +
        Copy(JsonContent, LastBrace, Length(JsonContent) - LastBrace + 1)
    else
      JsonContent :=
        Copy(JsonContent, 1, LastBrace - 1) + NewEntry +
        Copy(JsonContent, LastBrace, Length(JsonContent) - LastBrace + 1);
  end;

  SaveStringToFile(PrefsFile, JsonContent, False);
end;

function ShouldInstallVC: Boolean;
begin
  Result := InstallVC;
end;

function ShouldInstallWV2: Boolean;
begin
  Result := InstallWV2;
end;

procedure InitializeWizard;
begin
  InstallVC  := VCRedistNeedsInstall;
  InstallWV2 := WebView2NeedsInstall;
  CreateComponentsPage;
  CreateBooksPage;
end;

// שמירת בחירות בלחיצת "הבא"
function NextButtonClick(CurPageID: Integer): Boolean;
begin
  Result := True;
  if (CompPage <> nil) and (CurPageID = CompPage.ID) then
  begin
    InstallVC  := VCCheck.Checked;
    InstallWV2 := WV2Check.Checked;
  end;
  if (BooksPage <> nil) and (CurPageID = BooksPage.ID) then
  begin
    SelectedBooksPath := BooksPathEdit.Text;
    if SelectedBooksPath = '' then
    begin
      MsgBox('יש לבחור נתיב לתיקיית הספרים.', mbError, MB_OK);
      Result := False;
    end;
  end;
end;

procedure ExtractBundledDatabase(const ArchiveName, DatabaseName: String);
var
  ArchivePath, DatabasePath, ZstdPath, Params: String;
  ResultCode: Integer;
begin
  ArchivePath := ExpandConstant('{app}\_staging\' + ArchiveName);
  if not FileExists(ArchivePath) then
  begin
    Log('Bundled database archive not found, skipping: ' + ArchivePath);
    exit;
  end;

  DatabasePath := SelectedBooksPath + '\' + DatabaseName;
  ZstdPath := ExpandConstant('{app}\zstd.exe');

  ForceDirectories(ExtractFileDir(DatabasePath));

  Log('Extracting bundled database from ' + ArchivePath);
  Params := '-d -f -T0 --long=31 "' + ArchivePath + '" -o "' + DatabasePath + '"';

  if (not Exec(ZstdPath, Params, '', SW_HIDE, ewWaitUntilTerminated, ResultCode)) or (ResultCode <> 0) then
  begin
    MsgBox('חילוץ מסד הנתונים נכשל. קוד יציאה: ' + IntToStr(ResultCode), mbCriticalError, MB_OK);
    Abort;
  end;

  DeleteFile(ArchivePath);
end;

procedure ExtractBundledTarArchive(const ArchiveName, TargetDirName: String);
var
  ArchivePath, TarPath, ParentDir, TargetDir, ZstdPath, SevenZipPath, Params: String;
  ResultCode: Integer;
begin
  ArchivePath := ExpandConstant('{app}\_staging\' + ArchiveName);
  if not FileExists(ArchivePath) then
  begin
    Log('Bundled archive not found, skipping: ' + ArchivePath);
    exit;
  end;

  ParentDir := SelectedBooksPath;
  TarPath := ParentDir + '\' + ChangeFileExt(ArchiveName, '');
  TargetDir := SelectedBooksPath + '\' + TargetDirName;
  ZstdPath := ExpandConstant('{app}\zstd.exe');
  SevenZipPath := ExpandConstant('{app}\7za.exe');

  if DirExists(TargetDir) then
  begin
    DelTree(TargetDir, True, True, True);
  end;

  Log('Extracting bundled tar archive from ' + ArchivePath);
  Params := '-d -f -T0 --long=31 "' + ArchivePath + '" -o "' + TarPath + '"';

  if (not Exec(ZstdPath, Params, '', SW_HIDE, ewWaitUntilTerminated, ResultCode)) or (ResultCode <> 0) then
  begin
    MsgBox('חילוץ ארכיון ה-PDF נכשל. קוד יציאה: ' + IntToStr(ResultCode), mbCriticalError, MB_OK);
    Abort;
  end;

  Params := 'x -y "' + TarPath + '" "-o' + ParentDir + '"';
  if (not Exec(SevenZipPath, Params, '', SW_HIDE, ewWaitUntilTerminated, ResultCode)) or
     (ResultCode <> 0) then
  begin
    MsgBox('פתיחת ארכיון ה-PDF נכשלה. קוד יציאה: ' + IntToStr(ResultCode), mbCriticalError, MB_OK);
    Abort;
  end;

  DeleteFile(TarPath);
  DeleteFile(ArchivePath);
  // Optional: Delete the bundled db directory since everything was extracted elsewhere
  // But maybe it's cleaner to handle this in a separate procedure if needed.
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  ZstdPath, SevenZipPath: String;
  AppDataPath: string;
  ErrorLogPath: string;
begin
  if CurStep = ssInstall then
  begin
    // מחק את לוג השגיאות הישן בכל התקנה/עדכון
    ErrorLogPath := ExpandConstant('{userappdata}\otzaria\logs\errors.txt');
    if FileExists(ErrorLogPath) then
      DeleteFile(ErrorLogPath);
    ErrorLogPath := ExpandConstant('{commonappdata}\otzaria\logs\errors.txt');
    if FileExists(ErrorLogPath) then
      DeleteFile(ErrorLogPath);

    if WizardIsTaskSelected('resetsettings') then
    begin
      AppDataPath := GetDataDir('');
      if DirExists(AppDataPath) then
        DelTree(AppDataPath, True, True, True);

      AppDataPath := ExpandConstant('{userappdata}\otzaria');
      if DirExists(AppDataPath) then
        DelTree(AppDataPath, True, True, True);

      AppDataPath := ExpandConstant('{commonappdata}\otzaria');
      if DirExists(AppDataPath) then
        DelTree(AppDataPath, True, True, True);

      AppDataPath := ExpandConstant('{localappdata}\otzaria');
      if DirExists(AppDataPath) then
        DelTree(AppDataPath, True, True, True);
        
      // Delete old settings and personal notes (in AppData/Roaming)
      AppDataPath := ExpandConstant('{userappdata}\com.example');
      if DirExists(AppDataPath) then
        DelTree(AppDataPath, True, True, True);
    end;
  end;

  if CurStep <> ssPostInstall then
    exit;

  ZstdPath := ExpandConstant('{app}\zstd.exe');
  SevenZipPath := ExpandConstant('{app}\7za.exe');

  if not FileExists(ZstdPath) then
  begin
    MsgBox('קובץ החילוץ zstd.exe לא נמצא. ההתקנה לא יכולה לחלץ את קבצי הספרייה המצורפים.', mbCriticalError, MB_OK);
    Abort;
  end;

  if not FileExists(SevenZipPath) then
  begin
    MsgBox('קובץ החילוץ 7za.exe לא נמצא. ההתקנה לא יכולה לחלץ את קבצי ה-PDF המצורפים.', mbCriticalError, MB_OK);
    Abort;
  end;

  ExtractBundledDatabase('seforim.db.zst', 'seforim.db');
  ExtractBundledDatabase('otzar-HB_catalog.db.zst', 'otzar-HB_catalog.db');
  ExtractBundledTarArchive('talmud_bavli_latest.tar.zst', 'תלמוד בבלי');
  DeleteFile(ZstdPath);
  DeleteFile(SevenZipPath);

  // Cleanup the temporary extraction directory
  DelTree(ExpandConstant('{app}\_staging'), True, True, True);

  // יצירת תיקיית הספרים בנתיב שבחר המשתמש (אם שונה מברירת המחדל)
  if SelectedBooksPath <> '' then
  begin
    ForceDirectories(SelectedBooksPath);
    WriteLibraryPathToPrefs(SelectedBooksPath);
  end;
end;

[Run]
Filename: "{tmp}\vc_redist.x64.exe"; Parameters: "/install /quiet /norestart"; StatusMsg: "מתקין Visual C++ Redistributable 2022..."; Flags: waituntilterminated; Check: ShouldInstallVC
Filename: "{tmp}\MicrosoftEdgeWebview2Setup.exe"; Parameters: "/silent /install"; StatusMsg: "מתקין Microsoft WebView2 Runtime..."; Flags: waituntilterminated; Check: ShouldInstallWV2
Filename: "{app}\{#MyAppExeName}"; Description: "הפעל את {#MyAppName}"; Flags: nowait postinstall skipifsilent

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "resetsettings"; Description: "איפוס הגדרות משתמש והסרת התקנות קודמות (מומלץ למעדכנים מגרסה < 0.9.80, שים לב: זה ימחק הערות אישיות!)"; Flags: unchecked

[Files]
; Copy DLL files without compression to prevent corruption
Source: "..\build\windows\x64\runner\Release\*.dll"; DestDir: "{app}"; Flags: ignoreversion nocompression
; Copy all other app files
Source: "..\build\windows\x64\runner\Release\*"; \
  Excludes: "*.dll"; \
    DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

; Copy compressed library assets and extraction tool for post-install extraction
Source: "library_db\seforim.db.zst"; DestDir: "{app}\_staging"; Flags: ignoreversion nocompression
Source: "library_db\otzar-HB_catalog.db.zst"; DestDir: "{app}\_staging"; Flags: ignoreversion nocompression
Source: "library_db\talmud_bavli_latest.tar.zst"; DestDir: "{app}\_staging"; Flags: ignoreversion nocompression
Source: "zstd.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "7za.exe"; DestDir: "{app}"; Flags: ignoreversion

; vc_redist.x64.exe — הגרסה הרשמית של Microsoft, כ-25MB במקום AIO (~50MB)
; כוללת את 2015/2017/2019/2022 תחת אותו מספר גרסה (14.x)
Source: "vc_redist.x64.exe"; DestDir: "{tmp}"; Flags: deleteafterinstall; Check: ShouldInstallVC
; MicrosoftEdgeWebview2Setup.exe — bootstrapper קטן (~2MB) שמוריד ומתקין WebView2
; נדרש על ידי flutter_inappwebview_windows; ב-Win10/11 עם Edge עדכני — כבר קיים
Source: "MicrosoftEdgeWebview2Setup.exe"; DestDir: "{tmp}"; Flags: deleteafterinstall; Check: ShouldInstallWV2

[INI]
Filename: "{app}\system_install.marker"; Section: "Install"; Key: "Mode"; String: "Admin"; Check: IsAdminInstallMode
